//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IService4")]
    public interface IService4 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/htmlOutput", ReplyAction="http://tempuri.org/IService4/htmlOutputResponse")]
        string htmlOutput(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService4/htmlOutput", ReplyAction="http://tempuri.org/IService4/htmlOutputResponse")]
        System.Threading.Tasks.Task<string> htmlOutputAsync(string tag, string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService4Channel : ConsoleApp1.ServiceReference4.IService4, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service4Client : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference4.IService4>, ConsoleApp1.ServiceReference4.IService4 {
        
        public Service4Client() {
        }
        
        public Service4Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service4Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service4Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service4Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string htmlOutput(string tag, string data) {
            return base.Channel.htmlOutput(tag, data);
        }
        
        public System.Threading.Tasks.Task<string> htmlOutputAsync(string tag, string data) {
            return base.Channel.htmlOutputAsync(tag, data);
        }
    }
}
