//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.IService5")]
    public interface IService5 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/sortNumbers", ReplyAction="http://tempuri.org/IService5/sortNumbersResponse")]
        string sortNumbers(string sortType, string numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/sortNumbers", ReplyAction="http://tempuri.org/IService5/sortNumbersResponse")]
        System.Threading.Tasks.Task<string> sortNumbersAsync(string sortType, string numbers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService5Channel : ConsoleApp1.ServiceReference5.IService5, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service5Client : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference5.IService5>, ConsoleApp1.ServiceReference5.IService5 {
        
        public Service5Client() {
        }
        
        public Service5Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service5Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service5Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service5Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sortNumbers(string sortType, string numbers) {
            return base.Channel.sortNumbers(sortType, numbers);
        }
        
        public System.Threading.Tasks.Task<string> sortNumbersAsync(string sortType, string numbers) {
            return base.Channel.sortNumbersAsync(sortType, numbers);
        }
    }
}
